# try:
#     numerator = 10
#     denominator = 0
    
#     result = numerator/denominator
    
#     print(result)
#     Except:
#     print("Error:denominator cannot be 0.")




# try:
#     print(x)
# except:
#     print("An expeption occurred")


# try:
#     print("Hello")
# except:
#     print("Something went wrong")
# else:
#     print("Nothing went wrong")  

# try:
#     print("X")
# except:
#     print("Something went wrong")
# finally:
#     print("The 'try except' is finished")


